### ISSUE TITLE
Author number seems to return more/less results than expected

### ISSUE THREAD

**Issue by marblestation** [adsabs/author_affiliation_service#16]
To reproduce:

1. Go to qa
2. Search author:"^accomazzi, A."
3. Click export - author affiliation
4. Select 1 author
5. There are 2 authors that appear (accomazzi and kurtz)

It could seem that 1 author means accomazzi + 1 person but then there are other second authors that are not showing up. In any case, it seems there is something unexpected going on.

**Comment by golnazads** [comment]
Added a bit more explanation to readme file on how the service is behaving
now.
https://github.com/golnazads/author_affiliation_service/blob/master/README.md

**Comment by aaccomazzi** [comment]
Here is a more direct example: selected 1 paper authored by myself and 4 other people, requested author-affiliation table with data for 1 author.  This should have just generated a spreadsheet with my name but Mike is also included.

![image](https://user-images.githubusercontent.com/910261/36645626-a0667e88-1a39-11e8-82cb-93ec6245cbd1.png)

**Comment by golnazads** [comment]
Sorry. Service was returning one too many. fixed.

On Sun, Feb 25, 2018 at 2:39 PM, Alberto Accomazzi <notifications@github.com

**Comment by marblestation** [comment]
Thanks @golnazads ! I move this to done in zenhub too.
